### ISSUE TITLE
shop

### ISSUE THREAD

**Issue by N0ich** [Ne02ptzero/Grog-Knight#19]
Working on shop, mostly done, still needs the tooltip when hovering over an item

**Comment by N0ich** [comment]
Needs a sprite, and a designated room

**Comment by Ne02ptzero** [comment]
Verification for an already used item todo

**Comment by N0ich** [comment]
Verification done, 
Problem with the shop despawn that isnt properly implemented, but the call is available.
Shop gotta respawn aswell when returning into the room

**Comment by N0ich** [comment]
respawn fixed as well as a few bugs. 
Sprite needed

**Comment by N0ich** [comment]
Closing for now
