### ISSUE TITLE
Advanced stats for items

### ISSUE THREAD

**Issue by Fakoc** [Ne02ptzero/Grog-Knight#34]
Todo: bonusSpeed, DmgReduc, bonusDmg

Check compatibility with drugs
Implement in Charac.cpp(equip/unequip) / Hero.cpp(takedmg)

**Comment by Fakoc** [comment]
Display stats in Tooltip

**Comment by Fakoc** [comment]
Stats implemented
Display in Tooltip
Drugs ok
More work to do on Drugs and more tests to do.

**Comment by Fakoc** [comment]
Work on collision hero / wall when using mdma

**Comment by Fakoc** [comment]
Mdma done. Advanced stats should perfectly work!

**Comment by superdrug** [comment]
Hi there!

**Comment by superdrug** [comment]
Need a good link to get a hold of that chick Mandy

**Comment by Ne02ptzero** [comment]
@superdrug [How to be a Gentleman](http://www.wikihow.com/Be-a-Gentleman)
