### ISSUE TITLE
Minor Menu equipement

### ISSUE THREAD

**Issue by valouche** [Ne02ptzero/Grog-Knight#40]
when you choose your equipement, 
it doesn't work :-). (sprites piles up instead of being replaced (si si ça veut dire quelque chose))

![screen shot 2015-10-19 at 17 11 41](https://cloud.githubusercontent.com/assets/6772881/10581731/832ce592-7684-11e5-8a37-58541dbff2b9.png)

**Comment by Ne02ptzero** [comment]
Same as #39

**Comment by Ne02ptzero** [comment]
This is not a bug.

For debug purpose, we set a default start-items (MenuCharacter.cpp:44)
So the condition for removing the background at equipment change is always false (MenuCharacter.cpp::_updateSelection).
But if you remove those sets, it is working fine.
